services:
  database_db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - .env
    ports:
      - "5432:5432"
  fastdemo_app:
    image: fastdemo_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - database_db
    environment:
      - .env

volumes:
  pgdata:
